### ISSUE TITLE
Download button sometimes doesn’t work

### ISSUE THREAD

**Issue by cewong2** [mnao305/fantia-dl-tool#103]
Found on some random posts that the button won't work, you can click on it, but it won't do anything.

Tried this over multiple environments:

MacOS, Mojave, Brave
               Chrome
Windows 10, edge
            Chrome

**Comment by mnao305** [comment]
@cewong2 
Thanks for reporting this!

If you don't mind, can you give me the post URL that causes the problem? I've never encountered this problem before.

**Comment by cewong2** [comment]
Sorry for the late reply. https://fantia.jp/posts/761554

**Comment by mnao305** [comment]
Thank you for sharing the URL. I was able to confirm the bug.

It seems that the emoji in the title is causing bad behavior. We will look into ways to fix it.

**Comment by mnao305** [comment]
@cewong2 
Hello!
I was able to fix the problem with version 3.3.2. Please try it after the update.
