### ISSUE TITLE
フォルダ機能が機能していない

### ISSUE THREAD

**Issue by NaokiSato102** [mnao305/fantia-dl-tool#144]
ダウンロードフォルダをDドライブに移してるのですが、そのせいかは知りませんが、機能してません。

**Comment by mnao305** [comment]
@NaokiSato102 
返信遅くなり申し訳ありません。
私の環境で同様にダウンロードフォルダをDドライブに移して試してみたところ、問題なく機能していそうでした。

「フォルダ機能が機能していない」というのは具体的にどういった問題が発生しているでしょうか？
ファイルはダウンロードされるがフォルダに入らずファイルがばらけてしまうという事でしょうか？

**Comment by NaokiSato102** [comment]
一応こちらにも環境をば
OS
Win10 Pro x65 20H2

ブラウザ
Cốc Cốc(DL機能強化版クロニウム派生ブラウザ) バージョン: 100.0.102 （32 ビット）

症状はおっしゃる通り、
「ファイルはダウンロードされるがフォルダに入らずファイルがばらけてしまうという事」です。
なお、名前も反映されていません。ほかのプラグインとの相性問題もあるかもしれませんが、そもそも相性問題が発生するのは問題かと思われます。

**Comment by NaokiSato102** [comment]
だいぶ遅くなってしまいましたが、相性の悪いプラグインがどれかを突き留めました。[Px Downloader](https://chrome.google.com/webstore/detail/px-downloader/bcbibglkpaimhgmoomembjhclhipoack?hl=ja)です。
これを有効にしていると、フォルダ生成と名前の反映ができていません。
これは相性問題だとすると向こう側にも対応を訴えたほうがよろしでしょうか？

**Comment by mnao305** [comment]
こちらの環境でも[Px Downloader](https://chrome.google.com/webstore/detail/px-downloader/bcbibglkpaimhgmoomembjhclhipoack?hl=ja)を使用して動作確認してみましたが、問題は再現できませんでした。
ブラウザ影響かもしれません。非対応とします。
