### ISSUE TITLE
動作していない

### ISSUE THREAD

**Issue by NaokiSato102** [mnao305/fantia-dl-tool#170]
私の環境だけかもしれませんが、動作していません。

**Comment by mnao305** [comment]
報告ありがとうございます。

私の環境では正常に動作していそうです。
使用しているOS、ブラウザのバージョンを教えていただけますか？

**Comment by NaokiSato102** [comment]
OS
Win10 Pro x65 20H2

ブラウザ
Cốc Cốc(DL機能強化版クロニウム派生ブラウザ) バージョン: 100.0.102 （32 ビット）

GIFアニメが含まれると動作しないようです。 動画、静画には反応していました。

**Comment by mnao305** [comment]
ありがとうございます。
初めて見るブラウザですね…こちらの方でも同じ環境で動作確認してみます。

**Comment by mnao305** [comment]
申し訳ありませんがGoogle Chrome以外は非対応とさせていただきます。
