### ISSUE TITLE
ダウンロード場所の変更、保存フォルダを作成しないなどのオプション、全体の一括DLなど

### ISSUE THREAD

**Issue by NeoKune** [mnao305/fantia-dl-tool#189]
お疲れ様です。すごく便利なツールで重宝しています。
要望になりますが、タイトルのようなものを実装する事は不可能でしょうか？
全体の一括DLは過去に出るようですが、DLできるものにはまだ組み込まれていないのでしょうか？

ダウンロード場所の変更や保存フォルダの件ですが
私は画像を特定のフォルダにまとめて保存しているので、DLしたものを指定の場所までアクセスして、フォルダを全て昇り
画像を全て切り取り選択した後、いつも保存している場所に貼り付け、残ったフォルダを全て削除する…という手順を行っています。

作業量が多く、些か手間であるのため、この辺をなんとかできる機能がほしいなぁと思っております。
pixiv fanbox downloaderやEX pixiv downloaderなどのアドオンはその辺の設定が柔軟に可能なので、そのような機能が理想ですね…

無理を言って申し訳ありません。陰ながらですが、応援しています。

**Comment by mnao305** [comment]
Chome download APIの制限によりデフォルトのダウンロードの保存先は変更できないようです。
https://developer.chrome.com/docs/extensions/reference/api/downloads?hl=ja#:~:text=%E7%B5%B6%E5%AF%BE%E3%83%91%E3%82%B9%E3%80%81%E7%A9%BA%E3%81%AE%E3%83%91%E3%82%B9%E3%80%81%E5%BE%8C%E6%96%B9%E5%8F%82%E7%85%A7%E3%80%8C..%E3%80%8D%E3%82%92%E5%90%AB%E3%82%80%E3%83%91%E3%82%B9%E3%81%AF%E3%80%81%E3%82%A8%E3%83%A9%E3%83%BC%E3%81%AB%E3%81%AA%E3%82%8A%E3%81%BE%E3%81%99%E3%80%82

フォルダー分けしない機能はv3.8.0でリリースされました。オプション画面から設定できます。
