### ISSUE TITLE
CSRF token missing from API calls, resulting in 403 Forbidden on page downloads

### ISSUE THREAD

**Issue by asdf1324** [mnao305/fantia-dl-tool#351]
When you click on the download all button, nothing happens and you can observe that the API request has failed with 403 forbidden in the console log;
![image](https://user-images.githubusercontent.com/19871820/215306939-f0066ecb-8ff6-4625-9c96-47dae50627cf.png)

![image](https://user-images.githubusercontent.com/19871820/215306913-d1faeee6-03be-4ee6-b752-6e11349b554b.png)
Comparing the request headers of the succeeded request from the page (left) and the failed request from the extension (right), one can observe that there is a `x-csrf-token` header missing from the request created by the extension.

![image](https://user-images.githubusercontent.com/19871820/215306829-f647803d-9fd5-40fb-82f3-589156cba429.png)
The CSRF token can be found in the page's HTML source.

**Comment by asdf1324** [comment]
Last time I used the tool was 6 days ago and it worked fine then, so this must be a recent change.

Modifying `fetchPostData` like this makes it work again (not that it's an elegant solution, by any means)
```ts
...
let csrfToken = (document.getElementsByName("csrf-token")[0] as HTMLMetaElement).content
const json = await ky.get(`https://fantia.jp/api/v1/posts/${id}`, {"headers": {"x-csrf-token": csrfToken}}).json<PostDataResponse>()
...
```

**Comment by mnao305** [comment]
週末直せたら直します。

**Comment by mnao305** [comment]
v3.5.3としてストアにアップロードしました。Googleの審査完了まで少々お待ちください:pray:

**Comment by asdf1324** [comment]
対応ありがとうございます！TSやJSにはあまり自信がなくてPR送るのは無理でした😅

**Comment by mnao305** [comment]
v3.5.3として公開され、問題なくダウンロードできることが確認できました！

また何かあればお気軽にIssueを立ててください:bow:
