### ISSUE TITLE
投稿タイトルに特殊文字が含まれる場合、Invalid Filenameエラーが発生しダウンロードが開始されない。

### ISSUE THREAD

**Issue by meto4d** [mnao305/fantia-dl-tool#398]
投稿タイトルに[U+202A]などの制御文字を含んだ文字列の場合、background/index.jsのfilepathがそのまま特殊文字を含んでしまい、
保存する際に`r.reject(new Error(e.runtime.lastError.message))`にて"Invalid Filename"のエラーが発生、一括DLが行えない様です。

そこで簡易的に
```
g.browser.runtime.onMessage.addListener((e) => {
let arr = e.filepath.split("/");
for(let index in arr){
    arr[index] = arr[index].replace(/[\u202A-\u202c]/g, '');
}
e.filepath = arr.join("/");
"download" === e.msg && (0, r.L)(e.url, e.filename, e.filepath);
});
```
とすることで一括DLすることができました。

filepathないしfilenameに対して、何かしらのvalidate処理が必要かもしれません。

**Comment by mnao305** [comment]
@meto4d 

報告ありがとうございます！

制御文字を取り除く処理を追加したバージョン3.5.4をリリースしました。
アップデート後にお試しください:pray:

**Comment by meto4d** [comment]
@mnao305 

実際に問題のあった制御文字を含む投稿に対してテストしたところ、最新バージョンで問題なく一括DLすることができました。
迅速なご対応ありがとうございます！
