### ISSUE TITLE
一括DLが動作しなくなりました

### ISSUE THREAD

**Issue by supumari** [mnao305/fantia-dl-tool#427]
一括DLをクリックしても、ダウンロードが開始しません。
もしかしたら自分だけかもしれませんが、どの環境でも不具合が発生しているならば対処いただけますと助かります。

また、もしも私の環境でのみ発生しているのであれば、どういった情報をお伝えすればいいか教えていただけると助かります。

**Comment by Laydock12** [comment]
私も同じ症状です。 Windows10  Chrome バージョン: 114.0.5735.199（Official Build） （64 ビット）にて同様の症状です。
7/6  午前0時には動作しているのを確認しております。
また　Fantiaさんの構造が変わっった可能性がありますので　作者様　ぜひ調査をお願い致します。

**Comment by mnao305** [comment]
情報ありがとうございます。こちらでも機能していないのが確認できました。
調査してみます:bow:

**Comment by mnao305** [comment]
Fantia側の変更があったようです。
先程修正して、現在Googleによる審査待ちです。公開までもう少々お待ちください:pray:

**Comment by mnao305** [comment]
@supumari @Laydock12 
この問題が修正されたバージョン3.5.5が公開されました！
バージョンアップ後に再度お試しください:bow:

また、この問題を報告していただきありがとうございました。

**Comment by Laydock12** [comment]
素早いご対応ありがとうございます！！

**Comment by supumari** [comment]
即日の対応、誠にありがとうございます。
「大量の画像をzip無しで投稿されても困るな……」という悩みを解決できる、とても良い拡張機能で助けていただいています。
これからもどうぞよろしくお願いいたします。

**Comment by mnao305** [comment]
嬉しいコメントありがとうございます！
また何かあればお気軽にissueからお願いします🙇‍♂️
