### ISSUE TITLE
タイトル用写真と本文テキスト１件のみの投稿の場合

### ISSUE THREAD

**Issue by Laydock12** [mnao305/fantia-dl-tool#432]
タイトル用写真と本文テキスト１件のみの投稿の場合　一括DLボタンが表示されません。
またタイトル用画像は　一括DLボタンを押してもダウンロード対象になっていないためか
保存されないので　現状タイトル画像だけは　手動でDL＆Fantiaダウンローダーの組み合わせでDLしています。

タイトル画像も　一括DLボタンでの保存対象になっていただけると　手間が減るので助かります。
実装のご検討をお願いできればと思います。

よろしくお願いいたします。

**Comment by Laydock12** [comment]
同じタイプので変則的なものもやはり　今日落とせませんでしたので
なぜ落とせないのか　確認は可能でしょうか？

https://fantia.jp/posts/2162016

このようなページの作りの場合 一括DLボタンも表示されず　各画像の下にもDLボタンも出ません。
お忙しいとは思いますが、合わせてご確認をお願い致します。

**Comment by mnao305** [comment]
情報ありがとうございます。
現状の実装的にこの形式の投稿の場合、内容をただのテキストとしか解釈しておらず画像のダウンロードができないようです。
https://github.com/mnao305/fantia-dl-tool/blob/0a4dc3313a62c410ea030b4b9af95c4bf7e6ab09/src/content/modules/postPage.ts#L22-L26

またサムネイル画像のダウンロードの実装が漏れているようで、こちらもダウンロードできないようです。
後ほど修正いたします。

**Comment by mnao305** [comment]
すみません。教えていただいたようなページの場合の画像ダウンロードが簡単にはできなそうなので、一旦一括DLボタンの表示とサムネイル画像をダウンロードできるようにする修正をしたバージョン3.6.0をリリースしました。

リード文に埋め込まれている画像のダウンロードについてはもう少々お待ちください:bow:

**Comment by Laydock12** [comment]
お忙しいところ、早急な修正 ありがとうございます。
サムネイル画像が自動で落とせるようになっただけでも 今まで手動でDLしていた手間が省けて助かります。
感謝感謝です！！

2023年8月27日(日) 1:05 mnao305 ***@***.***>:

**Comment by Laydock12** [comment]
追加の報告です。
下記URLにあるような　サムネイルなし 本文テキストのみ　またはサムネイルなし　有料などの動画のみありの場合にも DLボタンが効いてないようです。　ご確認をお願い致します。

https://fantia.jp/posts/304420

https://fantia.jp/posts/292216

**Comment by mnao305** [comment]
情報ありがとうございます！
確かにDLボタンは表示されていますが機能していないですね…
確認してみます:bow:

**Comment by mnao305** [comment]
@Laydock12 

大変遅くなりましたが、こちらの対応が完了いたしました。
バージョン3.7.0として公開されたので、アップデートしてお試しください。

改めまして、Issueを立ててくださりありがとうございました。
また何かありましたらお気軽にIssueを立てて報告してください。

**Comment by Laydock12** [comment]
ありがとうございます。　先程 修正されているのを気づきました（汗
とても便利です。ありがとうございます！！
