### ISSUE TITLE
1月19日から Fantiaページ上にDLボタンが表示されなくなりました。

### ISSUE THREAD

**Issue by Laydock12** [mnao305/fantia-dl-tool#510]
お世話になっております。
昨日1/18までは　DLボタンが表示され 問題なく使えていたと思っていたのですが
本日1/19にFantiaにログインし 参加しているファンクラブページに行ってみても 拡張機能がまるで動いていないかのような状態です。
Fantia側の問題なのか？ 先日アップデートしたChromeの問題なのか わかないので報告させていただきます。

ご確認をお願いします。

こちらの使用環境は 
OS:Windows10 Pro　バージョン 22H2　OSビルド 19045.3930
Chrome：バージョン: 120.0.6099.225（Official Build） （64 ビット）

![fantia_bug_](https://github.com/mnao305/fantia-dl-tool/assets/123800867/de7c648d-6894-4646-a297-a30e103d91a5)

**Comment by Laydock12** [comment]
アップデート作業前の chrome 120.0.6099.217（Official Build） （64 ビット）でも
DLボタンの表示がされなくなっていましたので もしかするとFantia自体の問題の可能性もあることを
追記させていただきます。

**Comment by mnao305** [comment]
ご報告ありがとうございます！
どうやらFantia側の仕様変更による不具合のようです。

#509 にて対応される予定ですのでもう少々お待ちください 🙇

**Comment by mnao305** [comment]
@Laydock12 
対応が完了し先程v3.8.1として修正版をリリースしたので、バージョンアップのうえ再度お確かめください 🙇

改めましてご報告ありがとうございました。
また何かありましたらお気軽にIssueからお願いします。
