### ISSUE TITLE
テキストのみの投稿DL時に正常に動作しない

### ISSUE THREAD

**Issue by Desperatio0000** [mnao305/fantia-dl-tool#554]
タイトルの通り、テキストのみの投稿のDLを試みた際、
一部投稿で正常に動作しません。

①https://fantia.jp/posts/876441
②https://fantia.jp/posts/828207

①の投稿の場合は、限定コンテンツがDLされず
②の投稿の場合は、一括DLボタン押しても何もDLされません。
　（右クリックから「この投稿の全てをダウンロード」を押しても同様）

**Comment by mnao305** [comment]
報告ありがとうございます。こちらでも同様の挙動を確認できました。
どうやら投稿形式がblogのものだとダウンロードできないようでした。

現在等ツールはblog形式でのテキストのダウンロードに対応できていなかったため、今後機能追加できればと思います :bow:
https://github.com/mnao305/fantia-dl-tool/blob/10f25142e1efcb3ffb15ea4d0f26ea389cc0e38c/src/content/modules/blog.ts#L20

**Comment by mnao305** [comment]
@Desperatio0000 
v3.9.0にてテキストのダウンロードに対応しました。

バージョンアップ後に再度ダウンロードをお試しください。

**Comment by mnao305** [comment]
1週間経過したのでCloseします。
また何かありましたら再度Issueを立ててお知らせください 🙇‍♂️

**Comment by Desperatio0000** [comment]
DLできました！
対応ありがとうございました
