### ISSUE TITLE
テキストのみの投稿DL時に正常に動作しない-2

### ISSUE THREAD

**Issue by Desperatio0000** [mnao305/fantia-dl-tool#560]
blog形式の投稿の対応ありがとうございます。
以前DLできなかった投稿をDLしていたところ、
https://fantia.jp/posts/770189
https://fantia.jp/posts/762717
上記2つの投稿で一括DLボタン押しても何もDLされませんでした。
（フォルダも作成されず）

**Comment by mnao305** [comment]
ご報告ありがとうございます！

どうやらファイル名やフォルダ名に使用できない文字（`~`）があるのが原因のようでした。
後ほどこの文字を置き換えるようにする修正をいたします。

**Comment by mnao305** [comment]
@Desperatio0000 
v3.10.0にて修正しました。

バージョンアップ後に再度ダウンロードをお試しください。

**Comment by Desperatio0000** [comment]
DLできました！
対応ありがとうございました！
