### ISSUE TITLE
一括ボタンが機能していない

### ISSUE THREAD

**Issue by suzumiyabi** [mnao305/fantia-dl-tool#62]
https://fantia.jp/posts/347482

最新版シークレットモードでこれ以外の拡張機能をオフにしてもDLできなかった

**Comment by mnao305** [comment]
報告ありがとうございます！

私の環境でも当該記事でダウンロードした画像が1枚のみになってしまう現象を確認できました。
修正いたします:bow:

**Comment by mnao305** [comment]
バージョン2.0.1にて修正いたしました。Googleの審査が通り次第公開される予定です。

この度は報告ありがとうございました。
また何かあればお気軽にIssueをopenしてください。
